### ISSUE TITLE
[Feedback] Support for other grammar files? + Error display

### ISSUE THREAD

**Issue by TheWitheredStriker** [Nixinova/LightShowSite#1]
Hello!

Was wondering if you could potentially consider adding support for non-YAML-based grammar files at some point in the future (like JSON, CSON, XML etc). It's a bit irritating having to try to either find YAML grammars or having to try to convert other grammars (which doesn't work for me).

It'd also be useful to have some sort of "marker" that appears when NL fails to highlight the grammar (e.g. dysfunctional grammar file). Right now, nothing appears at all when you click the button and it doesn't work, which is not too clear imo. 

Thanks again for making this!

**Comment by Nixinova** [comment]
Apologies for the late reply, I missed this notif.
This project uses web ESM modules and I remember trying to get a converter but the npm packages didn't seem to work when loaded in the browser.
I will have another look at finding a package that can do this, as I can tell that converting manually would be quite annoying.

**Comment by Nixinova** [comment]
Try it out now, it should support JSON + CSON + PLIST now :+1:

**Comment by TheWitheredStriker** [comment]
Awesome! Thank you!
